export const storeAdminStyles = {
  main: 'mx-auto flex max-w-6xl flex-col gap-6 p-6',
  title: 'font-serif text-2xl',
  errorBox: 'rounded-box border border-error/40 p-10 text-center',
  errorTitle: 'font-serif text-lg',
  errorBody: 'mt-2 text-sm text-base-content/70',
  retryButton: 'btn btn-outline btn-sm mt-4',
  loadingBox: 'flex items-center gap-3 rounded-box border border-base-300 p-10',
  spinner: 'loading loading-spinner',
  nav: 'navbar border-b border-base-300 bg-base-100 px-6',
  navBrand: 'flex-1 font-serif text-lg',
  navActions: 'flex flex-none items-center gap-3',
  navEmail: 'hidden text-sm text-base-content/70 sm:inline',
  signOutButton: 'btn btn-ghost btn-sm',
}
