export const promotionMessages = {
  admin: {
    title: 'Promociones',
    subtitle: 'Descuentos por tiempo limitado sobre una técnica o un paquete.',
    newPromotion: 'Nueva promoción',
    columns: {
      target: 'Aplica a',
      discount: 'Descuento',
      window: 'Vigencia',
      status: 'Estado',
      actions: 'Acciones',
    },
    targetType: { technique: 'Técnica', package: 'Paquete' },
    status: {
      active: 'Vigente',
      expired: 'Vencida',
      paused: 'Pausada',
    },
    pagination: {
      label: 'Páginas de promociones',
      previous: 'Anterior',
      next: 'Siguiente',
      page: 'Página',
      of: 'de',
    },
    rowActions: { edit: 'Editar', deactivate: 'Pausar' },
    discountSuffix: '%',
    windowSeparator: '–',
    empty: {
      title: 'Todavía no hay promociones',
      body: 'Creá la primera promoción sobre una técnica o un paquete del catálogo.',
      cta: 'Crear la primera promoción',
    },
    loading: 'Cargando las promociones…',
    error: {
      title: 'No se pudieron cargar las promociones',
      body: 'Ocurrió un error al leer las promociones del catálogo.',
      retry: 'Reintentar',
    },
  },
  form: {
    legendCreate: 'Nueva promoción',
    legendEdit: 'Editar promoción',
    fields: {
      targetType: 'Servicio aplicable',
      targetTechnique: 'Técnica',
      targetPackage: 'Paquete',
      discountPercent: 'Descuento (%)',
      selectPlaceholder: 'Elegí una opción',
      startsAt: 'Empieza',
      endsAt: 'Termina',
    },
    submitCreate: 'Crear promoción',
    submitEdit: 'Guardar cambios',
    cancel: 'Cancelar',
    accessDenied:
      'Tu sesión no tiene permisos para modificar las promociones. Iniciá sesión como administradora.',
    validationTitle: 'Revisá estos campos:',
    savedCreate: 'Promoción creada.',
    savedEdit: 'Cambios guardados.',
    deactivated: 'Promoción pausada.',
    validation: {
      targetType: 'Elegí si aplica a una técnica o a un paquete',
      targetId: 'Elegí el servicio aplicable',
      discountPercent: 'El descuento debe ser un entero entre 1 y 100',
      startsAt: 'La fecha de inicio es obligatoria',
      endsAt: 'La fecha de fin es obligatoria',
    },
  },
} as const
