export const productStrings = {
  admin: {
    title: 'Productos de la tienda',
    subtitle: 'Productos de mantenimiento del catálogo público. El sitio lee de aquí.',
    newProduct: 'Nuevo producto',
    columns: {
      name: 'Producto',
      slug: 'Slug',
      price: 'Precio',
      order: 'Orden',
      stock: 'Existencias',
      status: 'Estado',
      actions: 'Acciones',
    },
    status: { active: 'Activo', inactive: 'Desactivado' },
    rowActions: { edit: 'Editar', deactivate: 'Desactivar', activate: 'Activar' },
    empty: {
      title: 'Todavía no hay productos',
      body: 'Creá el primer producto para que aparezca en el catálogo público.',
      cta: 'Crear el primer producto',
    },
    loading: 'Cargando los productos…',
    error: {
      title: 'No se pudo cargar el catálogo',
      body: 'Ocurrió un error al leer los productos.',
      retry: 'Reintentar',
    },
  },
  form: {
    legendCreate: 'Nuevo producto',
    legendEdit: 'Editar producto',
    fields: {
      name: 'Nombre',
      description: 'Descripción',
      imageUrl: 'URL de la imagen',
      priceCrc: 'Precio (colones)',
      displayOrder: 'Orden de presentación',
      stock: 'Existencias (unidades disponibles)',
    },
    submitCreate: 'Crear producto',
    submitEdit: 'Guardar cambios',
    cancel: 'Cancelar',
    accessDenied:
      'Tu sesión no tiene permisos para modificar el catálogo. Iniciá sesión como administradora.',
    validationTitle: 'Revisá estos campos:',
    savedCreate: 'Producto creado.',
    savedEdit: 'Cambios guardados.',
    deactivated: 'Producto desactivado.',
    activated: 'Producto activado: vuelve a verse en la tienda.',
    validation: {
      name: 'El nombre es obligatorio',
      nameWithoutLetters: 'El nombre necesita al menos una letra o un número',
      imageUrl: 'La URL de la imagen es obligatoria',
      priceCrc: 'El precio debe ser mayor que cero',
      displayOrder: 'El orden de presentación no puede ser negativo',
      stockRequired: 'Las existencias son obligatorias',
      stock: 'Las existencias deben ser un número entero, cero o mayor',
    },
  },
  shell: {
    brand: 'LASHARY',
    signOut: 'Cerrar sesión',
  },
} as const
