export const exemptClientFormStyles = {
  section: 'flex flex-col gap-4',
  heading: 'font-serif text-xl',
  subtitle: 'text-sm text-base-content/70',
  alertSuccess: 'alert alert-success',
  alertWarning: 'alert alert-warning',
  alertError: 'alert alert-error',
  feedbackTitle: 'font-medium',
  feedbackList: 'list-disc pl-5',
  searchRow: 'flex flex-col gap-2 sm:flex-row sm:items-end',
  fieldLabel: 'form-control w-full',
  labelText: 'label-text',
  fieldInput: 'input input-bordered w-full',
  searchButton: 'btn btn-outline sm:w-fit',
  statusText: 'text-sm text-base-content/70',
  resultsList: 'flex flex-col gap-1',
  result: 'btn btn-ghost btn-sm justify-start normal-case',
  resultSelected: 'btn btn-ghost btn-sm btn-active justify-start normal-case',
  selectedLine: 'text-sm',
  form: 'flex flex-col gap-4 border-t border-base-300 pt-4',
  textarea: 'textarea textarea-bordered w-full',
  submitButton: 'btn btn-primary w-fit',
}
