export const packageFormStyles = {
  fieldLabel: 'form-control w-full',
  labelText: 'label-text',
  fieldInput: 'input input-bordered w-full',
  alertSuccess: 'alert alert-success',
  alertWarning: 'alert alert-warning',
  alertError: 'alert alert-error',
  feedbackTitle: 'font-medium',
  feedbackList: 'list-disc pl-5',
  section: 'flex flex-col gap-4',
  heading: 'font-serif text-xl',
  form: 'grid gap-4',
  techniquesFieldset: 'form-control w-full rounded-box border border-base-300 p-4',
  techniquesList: 'flex flex-col gap-2',
  techniqueOption: 'label cursor-pointer justify-start gap-3',
  checkbox: 'checkbox checkbox-sm',
  durationTotal: 'text-sm text-base-content/70',
  submitWrapper: '',
  submitButton: 'btn btn-primary',
  deactivateForm: 'flex flex-col gap-2 border-t border-base-300 pt-4',
  deactivateButton: 'btn btn-outline btn-error w-fit',
}
