export const techniqueFormStyles = {
  fieldLabel: 'form-control w-full',
  labelText: 'label-text',
  fieldInput: 'input input-bordered w-full',
  alertSuccess: 'alert alert-success',
  alertWarning: 'alert alert-warning',
  alertError: 'alert alert-error',
  feedbackTitle: 'font-medium',
  feedbackList: 'list-disc pl-5',
  section: 'flex flex-col gap-4',
  heading: 'font-serif text-xl',
  form: 'grid gap-4 sm:grid-cols-2',
  select: 'select select-bordered w-full',
  aftercareLabel: 'form-control w-full sm:col-span-2',
  textarea: 'textarea textarea-bordered w-full',
  submitWrapper: 'sm:col-span-2',
  submitButton: 'btn btn-primary',
  deactivateForm: 'flex flex-col gap-2 border-t border-base-300 pt-4',
  deactivateButton: 'btn btn-outline btn-error w-fit',
}
