export const publicProductsGridStyles = {
  card: 'group card bg-base-100 shadow-sm transition duration-300 hover:shadow-xl motion-safe:hover:-translate-y-1',
  figure: 'overflow-hidden',
  image: 'h-56 w-full object-cover transition-transform duration-500 motion-safe:group-hover:scale-105',
  cardBody: 'card-body gap-1',
  cardTitle: 'card-title font-serif text-xl text-brand-dark',
  price: 'text-sm font-semibold uppercase tracking-wide text-primary',
  cardActions: 'card-actions mt-3 justify-end',
  viewMoreButton: 'btn btn-primary btn-sm',
  srOnly: 'sr-only',
  alert: 'alert',
  alertError: 'alert alert-error',
  alertTitle: 'font-semibold',
  retryButton: 'btn btn-sm btn-outline mt-3',
  grid: 'grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3',
}
