export const promotionFormStyles = {
  fieldLabel: 'form-control w-full',
  labelText: 'label-text',
  fieldInput: 'input input-bordered w-full',
  fieldSelect: 'select select-bordered w-full',
  alertWarning: 'alert alert-warning',
  section: 'flex flex-col gap-4',
  heading: 'font-serif text-xl',
  form: 'grid gap-4',
  targetTypeFieldset: 'form-control w-full',
  targetTypeOptions: 'flex gap-4',
  radioOption: 'label cursor-pointer gap-2',
  radio: 'radio radio-sm',
  submitWrapper: '',
  submitButton: 'btn btn-primary',
  deactivateForm: 'flex flex-col gap-2 border-t border-base-300 pt-4',
  deactivateButton: 'btn btn-outline btn-error w-fit',
}
