export { AddClientDialog } from './components/AddClientDialog'
export { AddClientButton } from './components/AddClientButton'
export { ClientModal } from './components/ClientModal'
export { ClientForm } from './components/ClientForm'
export { ClientFormField } from './components/ClientFormField'
export { ConfirmDialog } from './components/ConfirmDialog'
export { ClientsList } from './components/ClientsList'
export { useClientForm } from './hooks/useClientForm'
export { useFocusTrap } from './hooks/useFocusTrap'
export { createClientAction, listClientsAction } from './actions/clients-actions'
export { validateClientForm, hasClientFormErrors } from './validation/validate-client-form'
export { normalizePhone } from './validation/normalize-phone'
export { CLIENTS_LABELS, CLIENTS_BUTTON_TEXTS, CLIENTS_ERROR_MESSAGES, CLIENTS_PLACEHOLDERS, CLIENTS_CONFIRM_MESSAGES, CLIENTS_ARIA_LABELS } from './constants/clients-strings'
export { CLIENT_FIELD_KEYS, CLIENT_FORM_LIMITS, REQUIRED_CLIENT_FIELDS, EMPTY_CLIENT_FORM_VALUES, CLIENT_PHONE_FORMAT, CLIENTS_LIST_LIMITS, type ClientFieldKey } from './constants/client-form'
export type { ClientFormValues, ClientFormErrors } from './types/client-form.types'
export type { ClientRecord } from './types/client.types'
export type { SaveClientResult, ListClientsResult } from './types/client-actions.types'
