export { AddClientDialog } from './components/AddClientDialog'
export { AddClientButton } from './components/AddClientButton'
export { AddClientModal } from './components/AddClientModal'
export { AddClientForm } from './components/AddClientForm'
export { ClientFormField } from './components/ClientFormField'
export { ConfirmDialog } from './components/ConfirmDialog'
export { useAddClientForm } from './hooks/useAddClientForm'
export { useFocusTrap } from './hooks/useFocusTrap'
export { validateClientForm, hasClientFormErrors } from './validation/validate-client-form'
export { CLIENTS_LABELS, CLIENTS_BUTTON_TEXTS, CLIENTS_ERROR_MESSAGES, CLIENTS_PLACEHOLDERS, CLIENTS_CONFIRM_MESSAGES } from './constants/clients-strings'
export { CLIENT_FIELD_KEYS, CLIENT_FORM_LIMITS, REQUIRED_CLIENT_FIELDS, type ClientFieldKey } from './constants/client-form'
export type { ClientFormValues, ClientFormErrors } from './types/client-form.types'
