export { listClients } from './actions/list-clients'
export { AddClientDialog } from './components/AddClientDialog'
export { AddClientButton } from './components/AddClientButton'
export { EditClientDialog } from './components/EditClientDialog'
export { ClientModal } from './components/shared/ClientModal'
export { ClientForm } from './components/shared/ClientForm'
export { ClientFormField } from './components/ClientFormField'
export { ConfirmDialog } from './components/shared/ConfirmDialog'
export { ClientsList } from './components/ClientsList'
export { useClientForm } from './hooks/useClientForm'
export { useClientFormDialog } from './hooks/useClientFormDialog'
export { useFocusTrap } from './hooks/useFocusTrap'
export { validateClientForm, hasClientFormErrors } from './validation/validate-client-form'
export { CLIENTS_LABELS, CLIENTS_BUTTON_TEXTS, CLIENTS_ERROR_MESSAGES, CLIENTS_PLACEHOLDERS, CLIENTS_CONFIRM_MESSAGES, CLIENTS_ARIA_LABELS } from './constants/clients-strings'
export { CLIENT_FIELD_KEYS, CLIENT_FORM_LIMITS, REQUIRED_CLIENT_FIELDS, EMPTY_CLIENT_FORM_VALUES, type ClientFieldKey } from './constants/client-form'
export type { ClientFormValues, ClientFormErrors } from './types/client-form.types'
export type { ClientRecord } from './types/client.types'
export type { ClientProfileRow, ClientsListResult } from './types/client-row.types'
export { CLIENTS_LIST_LIMIT, CLIENTS_LIST_COLUMNS } from './constants/clients-query'
export { SAMPLE_CLIENTS } from './constants/sample-clients'
