export const packageFormStyles = {
  fieldLabel: 'form-control w-full',
  labelText: 'label-text',
  fieldInput: 'input input-bordered w-full',
  alertWarning: 'alert alert-warning',
  section: 'flex flex-col gap-4',
  heading: 'font-serif text-xl',
  form: 'grid gap-4',
  techniquesFieldset: 'form-control w-full rounded-box border border-base-300 p-4',
  techniquesList: 'flex flex-col gap-2',
  techniqueOption: 'label cursor-pointer justify-start gap-3',
  checkbox: 'checkbox checkbox-sm',
  inactiveBadge: 'badge badge-warning badge-sm',
  durationTotal: 'text-sm text-base-content/70',
  submitWrapper: '',
  submitButton: 'btn btn-primary',
  manageSection: 'flex flex-wrap items-start justify-between gap-4 border-t border-base-300 pt-4',
}
